---
- name: update apt
  apt: update_cache=yes

- name: install redis
  apt: 
    state: present
  pkg: [
    'redis-server',
    'redis-tools'
  ]
  notify:
    - restart redis
    
- name: copy redis.conf over
  notify: restart redis
  template: src=redis.conf dest=/etc/redis/redis.conf
